### PR TITLE
I have fixed some typos in the guidelines

### PR DESCRIPTION
**Pull request by simo498**

### CODE REVIEW

**Review by gallottino — APPROVED** [review]

**Review by guerinoni — CHANGES_REQUESTED** [review]
Can you rebase the branch and keep single commit like
`Remove typos from README` (or similar)

If you need help for rebase, ping me :)

**Comment by simo498** [comment]
I should have rebased the branch, and there should't be conflicts right now

**Comment by guerinoni** [comment]
There are 10 commits but you basically did only 1 more then `main`

**Comment by simo498** [comment]
That's right, i'll create a new PR then, because i messed up some stuff i guess

**Pull request closed without merging**
