### PR TITLE
Fix inconsistency in the variable name

### LINKED ISSUE #70: Inconsistency in the variable name for opcode
In the processor logic, opcode is often called `op_code` or `opcode`. We have to decide which name to use definitely, in order not to confuse, not to have two variables doing the same thing, etc.

I propose `opcode`. It is easier to write and read. It also reflects the documentation better.

### PR DESCRIPTION
**Pull request by FedericoBruzzone**
Closes #70 

Signed-off-by: Federico Bruzzone <federico.bruzzone.i@gmail.com>

### CODE REVIEW

**Comment by FedericoBruzzone** [comment]
I'll take this issue

**Comment by guerinoni** [comment]
Looks good, need rebase :)

**Comment by guerinoni** [comment]
Another rebase :)
Commit suggestion `Rename to `op_code` in all code`

**Review by guerinoni — APPROVED** [review]
LGTM

**Pull request merged**
